"""migration at 202204022309

Revision ID: 04b0136724ca
Revises: ffe77c89795d
Create Date: 2022-04-02 16:09:16.637940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04b0136724ca"
down_revision = "ffe77c89795d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
