"""migration at 202204022346

Revision ID: 5b80be498d37
Revises: b1c96f19ff34
Create Date: 2022-04-02 16:46:06.260551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b80be498d37'
down_revision = 'b1c96f19ff34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_placelist',
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('placelist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['placelist_id'], ['placelists.id'], )
    )
    op.drop_table('savedplaces')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savedplaces',
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('placelist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name='savedplaces_place_id_fkey'),
    sa.ForeignKeyConstraint(['placelist_id'], ['placelists.id'], name='savedplaces_placelist_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='savedplaces_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='savedplaces_pkey')
    )
    op.drop_table('place_placelist')
    # ### end Alembic commands ###
