"""migration at 202204022313

Revision ID: 7d079344d5b6
Revises: 865dc6d8937c
Create Date: 2022-04-02 16:13:49.681344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d079344d5b6'
down_revision = '865dc6d8937c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
