"""migration at 202204022311

Revision ID: 865dc6d8937c
Revises: 04b0136724ca
Create Date: 2022-04-02 16:11:53.610507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "865dc6d8937c"
down_revision = "04b0136724ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
