"""migration at 202204101708

Revision ID: 99194fa1d7ee
Revises: 5b80be498d37
Create Date: 2022-04-10 10:08:26.431377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99194fa1d7ee'
down_revision = '5b80be498d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'meta')
    # ### end Alembic commands ###
