"""migration at 202204022230

Revision ID: cb697b121368
Revises: f7b4cef6330c
Create Date: 2022-04-02 15:30:41.933626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb697b121368"
down_revision = "f7b4cef6330c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
