"""migration at 202204022223

Revision ID: f7b4cef6330c
Revises: f6896cf16db7
Create Date: 2022-04-02 15:23:28.300309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7b4cef6330c"
down_revision = "f6896cf16db7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("places", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "places", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "places", type_="foreignkey")
    op.drop_column("places", "owner_id")
    # ### end Alembic commands ###
